/**
 * ============================================================
 * NEXA Government PR Platform
 *
 * NEXA Scaffold Generator
 *
 * Version:
 * 0.3.0-alpha
 *
 * Features:
 * - Generate Module
 * - Generate Test
 * - Generate Documentation
 * - Auto Module Registry
 *
 * ============================================================
 */

import fs from "fs";
import path from "path";


const moduleName = process.argv[2];


if (!moduleName) {

    console.log(
`
Usage:

npm run create-module <module-name>

`
    );

    process.exit(1);

}



function toPascalCase(text){

    return text
        .split("-")
        .map(
            word =>
            word.charAt(0).toUpperCase()
            +
            word.slice(1)
        )
        .join("");

}



const className =
    toPascalCase(moduleName);



const modulePath =
    path.join(
        "src",
        "modules",
        moduleName
    );



const registryFile =
    path.join(
        "src",
        "modules",
        "index.js"
    );



const files = {};



files[
`NEXA.${className}.js`
]
=
`
/**
 * NEXA ${className}
 *
 * Generated by NEXA Scaffold Generator
 */

class NEXA${className} {


    constructor(options = {}){

        this.name =
        "${moduleName}";

        this.version =
        "1.0.0-alpha";

        this.options =
        options;

    }



    execute(data = {}){

        return {

            success:true,

            module:this.name,

            data

        };

    }


}



export default NEXA${className};

`;




files["index.js"]
=
`
import NEXA${className}
from "./NEXA.${className}.js";


export default function create${className}(options = {}){

    return new NEXA${className}(options);

}

`;




function updateRegistry(){


    let registry =
    fs.readFileSync(
        registryFile,
        "utf8"
    );



    const importLine =
`
import create${className}
from "./${moduleName}/index.js";
`;



    if(!registry.includes(importLine.trim())){

        registry =
        importLine
        +
        "\n"
        +
        registry;

    }




    const moduleLine =
`
    ${moduleName.replace(/-/g,"")}:
    create${className}(options),
`;



    if(!registry.includes(moduleLine.trim())){


        registry =
        registry.replace(

            "return {",

            "return {\n" +
            moduleLine

        );

    }



    fs.writeFileSync(
        registryFile,
        registry
    );


}




// Create folders

fs.mkdirSync(
    modulePath,
    {
        recursive:true
    }
);



fs.mkdirSync(
    path.join(modulePath,"tests"),
    {
        recursive:true
    }
);



fs.mkdirSync(
    path.join(modulePath,"docs"),
    {
        recursive:true
    }
);




// Write files

Object.entries(files)
.forEach(
([file,content])=>{


    fs.writeFileSync(

        path.join(
            modulePath,
            file
        ),

        content.trim()

    );


});





// Generate Test

fs.writeFileSync(

path.join(
modulePath,
"tests",
`${moduleName}-test.js`
),

`
console.log(
"NEXA ${className} Test Passed"
);
`

);





// Generate Docs

fs.writeFileSync(

path.join(
modulePath,
"docs",
`${moduleName}.md`
),

`
# NEXA ${className}

Version:
1.0.0-alpha

Module:
${moduleName}

`

);





// Update Registry

updateRegistry();





console.log(

`
=================================
NEXA Scaffold Generator v0.3.0
=================================

Module Created:

${moduleName}


Generated:

✓ Module
✓ Factory
✓ Test
✓ Documentation
✓ Registry Update


=================================
`

);