/**
 * ============================================================
 * NEXA Report Engine
 *
 * File: report.js
 * Version: 1.0.0
 *
 * Central Reporting Layer
 * ============================================================
 */


import {
    writeJSON,
    writeFile,
    createDirectory
}
from "./filesystem.js";



/**
 * Report Directory
 */
const REPORT_DIR =
"reports";



/**
 * Create Report Directory
 */
function ensureReportDirectory(){

    createDirectory(
        REPORT_DIR
    );

}



/**
 * Generate JSON Report
 */
export function createJSONReport(
    filename,
    data
){

    ensureReportDirectory();


    const filePath =
    `${REPORT_DIR}/${filename}`;


    writeJSON(
        filePath,
        data
    );


    return filePath;

}



/**
 * Generate Markdown Report
 */
export function createMarkdownReport(
    filename,
    title,
    sections = []
){

    ensureReportDirectory();


    let content = "";


    content += `# ${title}\n\n`;


    content +=
    `Generated by NEXA Report Engine\n\n`;


    content +=
    "=================================\n\n";


    sections.forEach(
        section => {

            content +=
            `## ${section.title}\n\n`;

            content +=
            `${section.content}\n\n`;

        }
    );


    const filePath =
    `${REPORT_DIR}/${filename}`;


    writeFile(
        filePath,
        content
    );


    return filePath;

}



/**
 * Quality Report
 */
export function createQualityReport(
    result
){

    return createJSONReport(
        "quality-report.json",
        {

            engine:
            "NEXA Quality Check Engine",

            timestamp:
            new Date().toISOString(),

            result

        }
    );

}



/**
 * Test Report
 */
export function createTestReport(
    result
){

    return createMarkdownReport(

        "test-report.md",

        "NEXA Test Automation Report",

        [

            {
                title:
                "Summary",

                content:
                JSON.stringify(
                    result,
                    null,
                    2
                )
            }

        ]

    );

}



/**
 * Release Report
 */
export function createReleaseReport(
    result
){

    return createMarkdownReport(

        "release-summary.md",

        "NEXA Release Summary",

        [

            {
                title:
                "Release Information",

                content:
                JSON.stringify(
                    result,
                    null,
                    2
                )

            }

        ]

    );

}